services:
  - type: web
    name: n8n
    env: docker
    dockerfilePath: ./Dockerfile.n8n  # 假設您有一個專門用於 n8n 的 Dockerfile
    dockerContext: .
    envVars:
      - key: TAIPEI_TIMEZONE
        value: Asia/Taipei
      - key: TZ
        value: Asia/Taipei
      - key: WEBHOOK_URL
        value: https://lottery-n8n.onrender.com
      - key: N8N_CORS
        value: https://lottery-n8n.onrender.com
    disk:
      name: n8n_data
      mountPath: /root/.n8n
      sizeGB: 1
    plan: free
    autoDeploy: true
    healthCheckPath: /

  - type: web
    name: python-app
    env: docker
    dockerfilePath: ./python-app/Dockerfile
    dockerContext: ./python-app
    envVars:
      - key: PYTHON_ENV
        value: production
    plan: free
    autoDeploy: true
    healthCheckPath: /