services:
  - type: web
    name: python-app
    env: docker
    dockerfilePath: ./python-app/Dockerfile
    dockerContext: ./python-app
    envVars:
      - key: PYTHON_ENV
        value: production
      - key: GITHUB_TOKEN
        sync: false
      - key: PORT
        value: 10000
    plan: free
    autoDeploy: true
    healthCheckPath: /health