services:
  - type: web
    name: n8n
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: TAIPEI_TIMEZONE
        value: Asia/Taipei
      - key: TZ
        value: Asia/Taipei
      - key: WEBHOOK_URL
        sync: false
      - key: N8N_CORS
        sync: false
      - key: N8N_ENCRYPTION_KEY
        sync: false
      - key: DB_TYPE
        value: postgresdb
      - key: DATABASE_URL
        vsync: false  # PostgreSQL URL
      - key: DB_POSTGRESDB_PASSWORD
        vsync: false  # PostgreSQL 使用者密碼
      - key: DB_POSTGRESDB_HOST
        sync: false # PostgreSQL 資料庫的主機地址
      - key: DB_POSTGRESDB_PORT
        value: "5432"  # 默認 PostgreSQL 端口
      - key: DB_POSTGRESDB_DATABASE
        sync: false  # PostgreSQL 資料庫名稱
      - key: DB_POSTGRESDB_USER
        sync: false # PostgreSQL 使用者
      - key: DB_POSTGRESDB_PASSWORD
        vsync: false  # PostgreSQL 使用者密碼
    plan: free
    autoDeploy: true
    healthCheckPath: /

  - type: web
    name: python-app
    env: docker
    dockerfilePath: ./python-app/Dockerfile
    dockerContext: ./python-app
    envVars:
      - key: PYTHON_ENV
        value: production
      - key: GITHUB_TOKEN
        sync: false
      - key: PORT
        value: 10000
    plan: free
    autoDeploy: true
    healthCheckPath: /health