services:
  - type: web
    name: n8n
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: TAIPEI_TIMEZONE
        value: Asia/Taipei
      - key: TZ
        value: Asia/Taipei
      - key: WEBHOOK_URL
        value: https://n8n-1zhw.onrender.com
      - key: N8N_CORS
        value: https://n8n-1zhw.onrender.com
      - key: GITHUB_TOKEN
        sync: false
    plan: free
    autoDeploy: true
    healthCheckPath: /

  - type: web
    name: python-app
    env: docker
    dockerfilePath: ./python-app/Dockerfile
    dockerContext: ./python-app
    envVars:
      - key: PYTHON_ENV
        value: production
      - key: GITHUB_TOKEN
        sync: false
      - key: PORT
        value: 10000
    plan: free
    autoDeploy: true
    healthCheckPath: /health
    healthCheckPort: 10000