services:
  - type: web
    name: n8n
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: TAIPEI_TIMEZONE
        value: Asia/Taipei
      - key: TZ
        value: Asia/Taipei
      - key: WEBHOOK_URL
        sync: false
      - key: N8N_CORS
        sync: false
      - key: N8N_ENCRYPTION_KEY
        sync: false
    plan: free
    autoDeploy: true
    healthCheckPath: /

  - type: web
    name: python-app
    env: docker
    dockerfilePath: ./python-app/Dockerfile
    dockerContext: ./python-app
    envVars:
      - key: PYTHON_ENV
        value: production
      - key: GITHUB_TOKEN
        sync: false
      - key: PORT
        value: 10000
    plan: free
    autoDeploy: true
    healthCheckPath: /health