services:
  - name: n8n
    type: web
    env: docker
    docker:
      image: n8nio/n8n
    envVars:
      - key: TAIPEI_TIMEZONE
        value: Asia/Taipei
      - key: TZ
        value: Asia/Taipei
      - key: WEBHOOK_URL
        value: https://lottery-n8n.onrender.com
      - key: N8N_CORS
        value: https://lottery-n8n.onrender.com
    disk:
      name: n8n_data
      mountPath: /root/.n8n
      sizeGB: 1
    plan: free
    autoDeploy: true
    healthCheckPath: /

  - name: python-app
    type: web
    env: docker
    docker:
      buildContext: ./python-app  
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    envVars:
      - key: PYTHON_ENV
        value: production
    plan: free
    autoDeploy: true
    healthCheckPath: /
